# ---- build ----
FROM oven/bun:alpine AS builder
WORKDIR /app

COPY package*.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .
RUN bun run build

# only prod dependencies
RUN bun prune --omit=dev

# ---- runtime ----
FROM oven/bun:alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV IS_DOCKER=true

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

CMD [ "node", "dist/index.js" ]